# Choose the Trainer and the Policy to train
trainer: "Trainer_SAC" # Trainer_PPO_IMITATION or Trainer_PPO_SIL

# Choose the Environment to load or "" for in Editor training
env_name:  "" # "./envs/CartPoleV1.exe"

# Choose trainer parameters passed to the trainer class
train_params: 

  # Number of epochs to run
  epochs: 1000
  # Steps per epoch
  steps_per_epoch: 300
  # max episode length -> termination
  max_episode_length: 150

  # discount factor
  gamma: 0.99
  # lambda factor for GAE
  lam: 0.97
  # starting seed for tensorflow and Env
  seed: 0

  # Training mode | Load the Model yes/no
  training: yes 
  load_model: no
  save_freq: 20
  
# Choose the policy parameters for training
policy_params:
  # learning rate Value Network
  lr_v:   0.001
  # leraning rate Policy Network
  lr_pi:  0.001
  # Update Iterations Pi and V
  train_pi_iters: 4
  train_v_iters: 4
  # Hidden Layers
  hidden_sizes_pi: [32,32]
  hidden_sizes_v: [32,32]
  # Hyperparameters Policy Update
  clip_ratio: 0.2
  target_kl: 0.01
  ent_coef: 0.1

# Self Imitation Learning Parameters
sil_params:
  # Use SIL yes/no
  use_sil: no
  batch_size_sil: 128
  # SIL Update iterations
  sil_iters: 10

bc_params:
  use_bc: yes
  batch_size_bc: 200
  iters_bc: 50
